  version: 2
  jobs:
    build:
      docker:
      - image: circleci/golang:1.11.0
      working_directory: /go/src/github.com/Setheck/oba
      steps:
      - checkout
      - run:
          name: Unit Test
          command: go test -v -cover ./...